### ISSUE TITLE
myhomemy rules

### ISSUE THREAD

**Issue by Shucai99** [Avankziar/MyHomeRules#1]
hallo wie  kann    ich zb bei Myhomesmyrules bei  gsgvo einen link  einfügen  oder den command weil  es geht nichtgeht das mfg

**Comment by Avankziar** [comment]
MHR stellt keine Links oder dedizierte Befehle für die DSGVO zu verfügung. Die musst du selbst bereitstellen.
Wie du nun einen Link hinzufügst:
- in der ger.yml oder der ger-mps.yml kannst du die Term: "~click@RUN_COMMAND@/dsgvolink" zu "~click@OPEN_URL@http://www.deinlink.de"
- wenn du nur einen Befehl einsetzten möchtest kannst du den Term so ändern:
  von "~click@RUN_COMMAND@/dsgvolink" zu "~click@RUN_COMMAND@/deinBefehl".

Falls das nicht verständlich ist, kann ich auch gerne live per Discord dir zeigen, wie das geht.
